### ISSUE TITLE
Users email is hardcoded

### ISSUE THREAD

**Issue by fleboulch** [ManoManoTech/homer#11]
Error message `Failed to to fetch slack user with emails ***` is displayed because it's hardcoded.  
[Line code](https://github.com/ManoManoTech/homer/blob/main/src/core/services/slack.ts#L98-L99)  

I can open an MR if you want

**Comment by greg0ire** [comment]
@fleboulch please do :pray:

**Comment by fleboulch** [comment]
Done @greg0ire :wink:
