### ISSUE TITLE
Open source the release and changelog feature

### ISSUE THREAD

**Issue by M0nkeySan** [ManoManoTech/homer#16]
# What

In the current **Manomano** internal project, homer offers the option of publishing and displaying a project's change log using the following commands : 

- `/homer changelog` Generate changelogs for any Gitlab project using release tags.
- `/homer release` Create a Gitlab release.
- `/homer release cancel` Cancel a Gitlab release.
- `/homer release end` End a Gitlab release.

These functionalities should be reviewed and modified to make them available in the open-source project.

# How

In order to add a releasable project, an internal configuration file must be modified. This behaviour needs to be reviewed to simplify the process and avoid the need to redeploy **homer** each time.

Firstly, we should externalise this configuration, and write documentation about it.
Then we could add a command like `/homer release enable` to register a new releaseable project.

The current configuration is as follows: 

```typescript
{
    notificationChannelIds: [
      IT_DEPLOY_CHANNEL_ID,
      FT_SELLER_CHANNEL_ID,
    ],
    projectId: 1,
    releaseChannelId: FT_SELLER_CHANNEL_ID,
    releaseManager: defaultReleaseManager,
    releaseTagManager: semanticReleaseTagManager,
  },
```

`projectId` : Gitlab project ID
`notificationChannelIds` : ID of the Slack channels that receive notifications about the release
`releaseChannelId` : ID of the slack channel where the release of the project is enabled
`releaseManager` : change depending on the type of the project (library, micro-service, frontend ..)
`releaseTagManager` : defines the tag naming (semantic, stable date ...)

The modal could be like this : 

![image](https://github.com/ManoManoTech/homer/assets/10235926/0c6cce5c-fee7-4a50-8eed-10ae4e6680a3)

**Comment by fleboulch** [comment]
I opened this [MR](https://github.com/ManoManoTech/homer/pull/17) before someone is working on this topic

**Comment by fleboulch** [comment]
This one can be closed
