### ISSUE TITLE
GITLAB_URL not loaded properly

### ISSUE THREAD

**Issue by pfongkye** [ManoManoTech/homer#28]
When using the docker image internally at my company, the [GITLAB_URL](https://github.com/ManoManoTech/homer/blob/main/src/constants.ts#L10) does not seem to load properly.

Steps to reproduce on internal Gitlab:
- Pull image from GitHub and build another one in internal Gitlab.
- Run the image on Gitlab pipeline with all env variables set.

An error in log mentioning `Environment variable GITLAB_URL not found`

**Comment by cicoub13** [comment]
I'm not able to reproduce with the Github image locally (GITLAB_URL is taken in account).
Same for internal MM image locally. It should come from pipeline or way to deploy
