### ISSUE TITLE
Can we use homer with a node version > 18?

### ISSUE THREAD

**Issue by fleboulch** [ManoManoTech/homer#32]
In the [prerequisites](https://github.com/ManoManoTech/homer?tab=readme-ov-file#3-prerequisites) you are talking about node 18.  
Can we use a newer version of node?

**Comment by cicoub13** [comment]
Hello. We never tested it but should work

https://github.com/ManoManoTech/homer/issues/33

**Comment by cicoub13** [comment]
Solved in #35

**Comment by fleboulch** [comment]
Thanks @cicoub13 for the work
