### ISSUE TITLE
Squash policy (github config)

### ISSUE THREAD

**Issue by fleboulch** [ManoManoTech/homer#41]
**Current behaviour**

Once a PR is merged all the commits are in the main branch. If I have 15 commits they will be all in main

**Expected behaviour**

1 commit per PR on the main branch

**Comment by cicoub13** [comment]
Done, thanks ✅

**Comment by greg0ire** [comment]
@cicoub13 We can make squash merge the default but I wouldn't make that the only option. When I make 3 commits, all of them are atomic, with good commit messages and I still want to be able to revert only one of them easily. Sorry for not speaking up sooner.

**Comment by cicoub13** [comment]
OK with you but I would like the squash option the default one 🤔

**Comment by cicoub13** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github

> You can enforce one type of merge method, such as commit squashing or rebasing, by only enabling the desired method for your repository.

**Comment by greg0ire** [comment]
@cicoub13 I wouldn't enforce anything. It's up to us maintainers to tell apart PRs with commits that look like this:
- main thing
- oopsie cs
- ah shit there's a bug with version X
- maybe that will fix it
- incorporate feedback from review

from PRs that look like this:
- main thing
- other unrelated small thing I'm fixing along the way, can be reverted independently
